# Generated by Django 4.2.5 on 2024-07-17 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipments',
            name='num',
            field=models.CharField(max_length=128, verbose_name='номер'),
        ),
    ]
