# Generated by Django 4.2.5 on 2023-12-08 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartproducts',
            name='quantity',
            field=models.DecimalField(decimal_places=4, max_digits=10, verbose_name='количество'),
        ),
    ]
