# Generated by Django 4.2.5 on 2024-01-12 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manufactures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_number', models.CharField(blank=True, max_length=40, null=True)),
                ('fix_number', models.CharField(blank=True, max_length=40, null=True)),
                ('num', models.CharField(max_length=128)),
                ('date_creation', models.DateField(verbose_name='дата создания')),
                ('date_production', models.DateField(verbose_name='дата производства')),
                ('date_fixation', models.DateField(blank=True, null=True, verbose_name='дата фиксации')),
                ('condition', models.CharField(choices=[('Отправлено', 'Отправлено'), ('Принято ЕГАИС', 'Принято ЕГАИС'), ('Отклонено ЕГАИС', 'Отклонено ЕГАИС'), ('Зафиксировано в ЕГАИС', 'Зафиксировано в ЕГАИС'), ('Распроведено', 'Распроведено')], max_length=40, verbose_name='cостояние')),
                ('uuid', models.UUIDField()),
                ('type_operation', models.CharField(choices=[('OperProduction', 'Производство'), ('OperConversion', 'Переработка'), ('OperMaterials', 'Производство сырья для собственного использования')], max_length=40, verbose_name='Тип операции')),
                ('footing', models.TextField(blank=True, null=True, verbose_name='основание')),
            ],
            options={
                'verbose_name': 'Производство',
                'verbose_name_plural': 'Производство',
                'ordering': ['date_creation'],
            },
        ),
        migrations.CreateModel(
            name='RecieveInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_number', models.CharField(max_length=40)),
                ('fix_number', models.CharField(max_length=40)),
                ('num', models.CharField(max_length=128)),
                ('date_creation', models.DateField(verbose_name='дата создания')),
                ('date_fixation', models.DateField(blank=True, null=True, verbose_name='дата фиксации')),
                ('condition', models.CharField(choices=[('Отправлено', 'Отправлено'), ('Принято ЕГАИС', 'Принято ЕГАИС'), ('Получено', 'Получено'), ('Отклонено ЕГАИС', 'Отклонено ЕГАИС'), ('Зафиксировано в ЕГАИС', 'Зафиксировано в ЕГАИС'), ('Проведено', 'Проведено'), ('Распроведено', 'Распроведено')], max_length=40, verbose_name='cостояние')),
                ('uuid', models.UUIDField()),
                ('footing', models.TextField(blank=True, null=True, verbose_name='основание')),
                ('change_ownership', models.CharField(choices=[('NotChange', 'Не меняется'), ('IsChange', 'Меняется')], max_length=30, verbose_name='право собственности')),
                ('train_company', models.CharField(max_length=255, verbose_name='перевозчик')),
                ('transport_number', models.CharField(max_length=50, verbose_name='номер автомобиля')),
                ('train_trailer', models.CharField(max_length=50, verbose_name='номер прицепа')),
                ('train_customer', models.CharField(max_length=255, verbose_name='заказчик')),
                ('driver', models.CharField(max_length=255, verbose_name='водитель')),
                ('redirection', models.CharField(max_length=255, verbose_name='перенаправление')),
                ('unload_point', models.TextField(verbose_name='место разгрузки')),
                ('dispetcher', models.CharField(max_length=255, verbose_name='экспедитор')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clients.clients')),
            ],
            options={
                'verbose_name': 'Сведение о получении',
                'verbose_name_plural': 'Сведения о получении',
                'ordering': ['date_creation'],
            },
        ),
        migrations.CreateModel(
            name='ManufacturedProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positions', models.IntegerField(verbose_name='позиция')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='количество')),
                ('alcovolume', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='крепость')),
                ('form1', models.CharField(blank=True, max_length=18, null=True, verbose_name='справка А')),
                ('form2', models.CharField(blank=True, max_length=18, null=True, verbose_name='справка Б')),
                ('batch_num', models.CharField(max_length=128, verbose_name='номер партии')),
                ('manufactures', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manufactures.manufactures')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.products', verbose_name='продукт')),
            ],
            options={
                'verbose_name_plural': 'Произведенная продукция',
            },
        ),
        migrations.CreateModel(
            name='ImportInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_number', models.CharField(max_length=40)),
                ('fix_number', models.CharField(max_length=40)),
                ('num', models.CharField(max_length=128)),
                ('date_creation', models.DateField(verbose_name='дата создания')),
                ('date_report', models.DateField(blank=True, null=True, verbose_name='дата отчета')),
                ('date_td', models.DateField(blank=True, null=True, verbose_name='дата ТД')),
                ('date_fixation', models.DateField(blank=True, null=True, verbose_name='дата фиксации')),
                ('condition', models.CharField(choices=[('Отправлено', 'Отправлено'), ('Принято ЕГАИС', 'Принято ЕГАИС'), ('Получено', 'Получено'), ('Отклонено ЕГАИС', 'Отклонено ЕГАИС'), ('Зафиксировано в ЕГАИС', 'Зафиксировано в ЕГАИС'), ('Проведено', 'Проведено'), ('Распроведено', 'Распроведено')], max_length=40, verbose_name='cостояние')),
                ('uuid', models.UUIDField()),
                ('footing', models.TextField(blank=True, null=True, verbose_name='основание')),
                ('num_td', models.CharField(max_length=128)),
                ('num_contract', models.CharField(max_length=128)),
                ('date_contract', models.DateField(verbose_name='дата контракта')),
                ('from_country', models.CharField(max_length=128)),
                ('receipt_of_imp', models.CharField(max_length=128)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clients.clients')),
            ],
            options={
                'verbose_name': 'Сведение о импорте',
                'verbose_name_plural': 'Сведения о импорте',
                'ordering': ['date_creation'],
            },
        ),
        migrations.CreateModel(
            name='ImportedProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positions', models.IntegerField(verbose_name='позиция')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='количество')),
                ('form1', models.CharField(blank=True, max_length=18, null=True, verbose_name='справка А')),
                ('form2', models.CharField(blank=True, max_length=18, null=True, verbose_name='справка Б')),
                ('batch_num', models.CharField(max_length=128, verbose_name='номер партии')),
                ('import_info', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manufactures.recieveinfo')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.products', verbose_name='продукт')),
            ],
            options={
                'verbose_name_plural': 'Импортированная продукция',
            },
        ),
        migrations.CreateModel(
            name='RecievedProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positions', models.IntegerField(verbose_name='позиция')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='количество')),
                ('form1', models.CharField(blank=True, max_length=18, null=True, verbose_name='справка А')),
                ('form2', models.CharField(blank=True, max_length=18, null=True, verbose_name='справка Б')),
                ('batch_num', models.CharField(max_length=128, verbose_name='номер партии')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.products', verbose_name='продукт')),
                ('receive_info', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manufactures.recieveinfo')),
            ],
            options={
                'verbose_name_plural': 'Полученная продукция',
                'indexes': [models.Index(fields=['-receive_info'], name='manufacture_receive_e5b705_idx')],
            },
        ),
        migrations.CreateModel(
            name='RawForManufactured',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positions', models.IntegerField(verbose_name='позиция')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='количество')),
                ('form2', models.CharField(max_length=18, verbose_name='справка Б')),
                ('mf_products', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manufactures.manufacturedproducts')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.products', verbose_name='продукт')),
            ],
            options={
                'verbose_name_plural': 'Использованное сырье',
                'indexes': [models.Index(fields=['-mf_products'], name='manufacture_mf_prod_d758d8_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProductResidues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='количество')),
                ('form1', models.CharField(blank=True, max_length=18, null=True, verbose_name='справка А')),
                ('form2_old', models.CharField(blank=True, max_length=18, null=True, verbose_name='справка Б')),
                ('form2_new', models.CharField(blank=True, max_length=18, null=True, verbose_name='присвоенная справка Б')),
                ('batch_num', models.CharField(max_length=128, verbose_name='номер партии')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clients.clients', verbose_name='производитель')),
                ('import_info', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manufactures.recieveinfo')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.products', verbose_name='продукт')),
            ],
            options={
                'verbose_name_plural': 'Остатки',
                'indexes': [models.Index(fields=['-product'], name='manufacture_product_c1c68b_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='manufacturedproducts',
            index=models.Index(fields=['-manufactures'], name='manufacture_manufac_36f464_idx'),
        ),
        migrations.AddIndex(
            model_name='importedproducts',
            index=models.Index(fields=['-import_info'], name='manufacture_import__ab8dab_idx'),
        ),
    ]
