# Generated by Django 4.2.5 on 2024-07-17 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufactures', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturedproducts',
            name='batch_num',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='номер партии'),
        ),
    ]
